repositoryUrl: git@github.com:mailstepcz/semantic-release-jira
branch: master
dryRun: false
debug: false
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/npm"
    - npmPublish: true
  - "@semantic-release/git"
  - - "@semantic-release/github"
    - failComment: false
